def guess_draw(guess)
  case guess
  when 1
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |           "
    puts "  |                     Previous Guesses: #{@guess.join(", ")}"
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 2
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |                     Previous Guesses: #{@guess.join(", ")}"
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 3
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |          |          Previous Guesses: #{@guess.join(", ")}"
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 4
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |          |          Previous Guesses: #{@guess.join(", ")}"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 5
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|         Previous Guesses: #{@guess.join(", ")}"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 6
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/        Previous Guesses: #{@guess.join(", ")}"
    puts "  |          |"
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  when 7
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/        Previous Guesses: #{@guess.join(", ")}"
    puts "  |          |"
    puts "  |         / "
    puts "__|\\____________"
    puts "\n"
  when 8
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |          |"
    puts "  |          O"
    puts "  |         \\|/        Previous Guesses: #{@guess.join(", ")}"
    puts "  |          |"
    puts "  |         / \\ "
    puts "__|\\____________"
    puts "\n"
  else
    puts "\n#{@print_guess.join(" ")}"
    puts "  ____________"
    puts "  |           "
    puts "  |           "
    puts "  |                     Previous Guesses: #{@guess.join(", ")}"
    puts "  |           "
    puts "  |           "
    puts "__|\\____________"
    puts "\n"
  end
end
